spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app
    username: root
    password: clushtaedy
  jpa:
    hibernate:
      ddl-auto: update

  # SpringDoc 설정
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    root: error # 기본 로그 레벨은 에러로 설정
    org.springframework.web: debug # 스프링 웹 로그 레벨
    com.example.demo: info # 애플리케이션의 API 관련 로그
  file:
    name: logs/api-requests.log # API 호출 로그 저장 파일
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 콘솔 출력 형식
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 파일 출력 형식

management:
  endpoints:
    web:
      exposure:
        include: "*"
